config {
    type: "table",
    schema: "day",
    name: "tb_day_trs_tmb001_emvusagerejectionsummary",
    tags: ["tmb005"],
    description: "Lista de assets ATM do TOPdesk"
}

SELECT
    id,
    CAST(date AS DATE) AS date,
    CAST(month AS DATE) AS month,
    toTransportOperatorId,
    toLineId,
    toTerminalCode,
    toTerminalGroupId,
    emvProductId,
    emvBinBin,
    brand,
    emvAidAid,
    rejectionCount,
    blameUser,
    CAST(createdAt AS TIMESTAMP) AS createdAt,
    CAST(updatedAt AS TIMESTAMP) AS updatedAt,
    CAST(LOWER(isReaderError) IN ('t','true') AS BOOL) AS isReaderError,
    tktRejectReasonCode,
    CAST(LOWER(transactionCompleted) IN ('t','true') AS BOOL) AS transactionCompleted,
    mode,
    "TMB001" AS origem,
    CURRENT_TIMESTAMP() AS dt_processamento,
    SESSION_USER() AS usuario_processamento
FROM
    ${ref("tb_ext_trs_tmb001_emvusagerejectionsummary")}

