config {
  type: "table",
  schema: "day",
  name: "tb_day_trs_tmb001_atm_pix",
  tags: ["tmb005"],
  description: "Lista de assets ATM do TOPdesk"
}

SELECT
    cod_atm,
    Estacao,
    Linha,
    Empresa,
    PARSE_TIMESTAMP('%d/%m/%Y %H:%M:%S', data_hora_trans) AS data_hora_trans,
    valor,
    valor_recebido,
    pix_txid,
    pix_endtoendid,
    produto,
    aplicacao,
    idtrn,
    pdv,
    DATETIME(CAST(ctm_datetime_tz AS TIMESTAMP), "America/Sao_Paulo") AS ctm_datetime_tz
FROM
    ${ref("tb_ext_trs_tmb001_atm_pix")}


    