config {
    type: "table",
    schema: "day",
    name: "tb_day_trs_tmb001_emvdebitrecoveryprocess",
    tags: ["tmb005"],
    description: "Lista de assets ATM do TOPdesk"
}

SELECT
    id,
    CAST(startProcess AS TIMESTAMP) AS startProcess,
    CAST(endProcess AS TIMESTAMP) AS endProcess,
    elapsedTime,
    CAST(isProcessed AS BOOL) AS isProcessed,
    CAST(createdAt AS TIMESTAMP) AS createdAt,
    CAST(updatedAt AS TIMESTAMP) AS updatedAt,
    blameUser,
    approvedCount,
    deniedCount,
    totalCount,
    errorCount,
    skippedCount,
    "TMB001" AS origem,
    CURRENT_TIMESTAMP() AS dt_processamento,
    SESSION_USER() AS usuario_processamento
FROM
    ${ref("tb_ext_trs_tmb001_emvdebitrecoveryprocess")}