config {
    type: "table",
    schema: "day",
    name: "tb_day_trs_tmb001_emvdebitrecovery",
    tags: ["tmb005"],
    description: "Lista de assets ATM do TOPdesk"
}

SELECT
  id,
  emvAcquirerCode,
  emvCardPanToken,
  emvPaymentId,
  emvOrigPaymentId,
  CAST(processDate AS TIMESTAMP) AS processDate,
  CAST(scheduleDate AS TIMESTAMP) AS scheduleDate,
  type,
  value,
  recoveryAttempt,
  CAST(createdAt AS TIMESTAMP) AS createdAt,
  CAST(updatedAt AS TIMESTAMP) AS updatedAt,
  blameUser,
  emvDebitRecoveryProcessId,
  CAST(hasEmvModeChanged AS BOOL) AS hasEmvModeChanged,
  paymentMode,
  CAST(isLastRecovery AS BOOL) AS isLastRecovery,
  emvOrigCardPanToken,
  emvParPar,
  CAST(isDebitRecoveryByPar AS BOOL) AS isDebitRecoveryByPar,
  CAST(isManuallyTriggered AS BOOL) AS isManuallyTriggered,
  CAST(isDammedRuleTriggered AS BOOL) AS isDammedRuleTriggered,
  CAST(isActive AS BOOL) AS isActive,
  inactivationReason,
  "TMB001" AS origem,
  CURRENT_TIMESTAMP() AS dt_processamento,
  SESSION_USER() AS usuario_processamento
FROM
  ${ref("tb_ext_trs_tmb001_emvdebitrecovery")}
