config {
    type: "table", // Criamos como tabela para ter os dados fisicamente no BQ
    schema: "his",
    name: "tb_his_mrd_tpd001_changetypes",
    description: "Camada Bronze: Dados persistidos como texto para garantir resiliência contra mudanças de schema",
    tags: ["topdesk"],
}


SELECT 
        id,
        name,
        order_changes_types
FROM ${ref("tb_day_mrd_tpd001_changetypes")}
