config {
  type: "table",
  schema: "his",
  name: "tb_his_trs_tpd001_changes",
  description: "Tabela de incidentes tipada e persistida via Merge Incremental",
  bigquery: {
    partitionBy: "DATE(creationDate)",
  },
  tags: ["topdesk"],
}

SELECT 
approveImplManagerGroup,
approveImplManagerId,

CAST(authorizationDate AS TIMESTAMP) AS authorizationDate,
authorizingOperatorId,
branchId,
budgetHolderId,

CAST(callDate AS TIMESTAMP) AS callDate,
callerBranchId,
CAST(cancellationDate AS TIMESTAMP) AS cancellationDate,

categoryId,
changeNumber,
changeType,

closed,
CAST(closureDate AS TIMESTAMP) AS closureDate,

coordinatorId,
CAST(costs AS FLOAT64) AS costs,

DATETIME(SAFE_CAST(`creationDate` AS TIMESTAMP), "America/Sao_Paulo") AS creationDate,
creatorId,

currentPhase,
CAST(currentPlannedCosts AS FLOAT64) AS currentPlannedCosts,
CAST(currentPlannedTimeSpent_inSeconds AS FLOAT64) AS currentPlannedTimeSpent_inSeconds,

departmentId,
emergencyChange,
CAST(estimatedCosts AS FLOAT64) AS estimatedCosts,
CAST(estimatedTimeSpent_inSeconds AS FLOAT64) AS estimatedTimeSpent_inSeconds,

evalChangeCanBeAuthorized,
CAST(extensiveChangeImplementationDate AS TIMESTAMP) AS extensiveChangeImplementationDate,

id,
impactId,

CAST(modificationDate AS TIMESTAMP) AS modificationDate,
modifierId,

operatorGroupId,
operatorId,
originalIncidentId,

CAST(originalPlannedCosts AS FLOAT64) AS originalPlannedCosts,
CAST(originalPlannedTimeSpent_inSeconds AS FLOAT64) AS originalPlannedTimeSpent_inSeconds,

CAST(plannedAuthorizationDate AS TIMESTAMP) AS plannedAuthorizationDate,
CAST(plannedFinalDate AS TIMESTAMP) AS plannedFinalDate,
CAST(plannedImplementationDate AS TIMESTAMP) AS plannedImplementationDate,
CAST(plannedStartDate AS TIMESTAMP) AS plannedStartDate,

preliminaryRFCManagerGroup,
preliminaryRFCManagerId,

priorityId,
processingStatusId,

progressChangeCanBeAuthorized,

CAST(realizedDate AS TIMESTAMP) AS realizedDate,
rejected,
CAST(rejectionDate AS TIMESTAMP) AS rejectionDate,

requestChangeCanBeAuthorized,
requesterId,

CAST(simpleChangeImplementationDate AS TIMESTAMP) AS simpleChangeImplementationDate,

CAST(startDate AS TIMESTAMP) AS startDate,
started,
status,
subcategoryId,

CAST(submissionDate AS TIMESTAMP) AS submissionDate,
supplierId,
templateId,

CAST(timeTaken_inSeconds AS FLOAT64) AS timeTaken_inSeconds,

typeId,
versionId,
withEvaluation
FROM dev-autopass-bi-001.day.tb_day_trs_tpd001_changes
