config {
    type: "table", // Criamos como tabela para ter os dados fisicamente no BQ
    schema: "his",
    name: "tb_his_mrd_tpd001_branches",
    description: "Camada Bronze: Dados persistidos como texto para garantir resiliência contra mudanças de schema",
    tags: ["topdesk"],
}


SELECT 
        VATnumber,
        accountManagerId,
        city,
        countryId,
        creationDate,
        customerReferenceNumber,
        extraAId,
        extraBId,
        headBranchId,
        id,
        mainContactId,
        modificationDate,
        name,
        serviceWindowId,
        status
FROM dev-autopass-bi-001.day.tb_day_mrd_tpd001_branches