config {
    type: "table", // Criamos como tabela para ter os dados fisicamente no BQ
    schema: "his",
    name: "tb_his_mrd_tpd001_operators",
    description: "Camada Bronze: Dados persistidos como texto para garantir resiliência contra mudanças de schema",
    tags: ["topdesk"],
}


SELECT 
        branchId,
        budgetHolderId,
        creationDate,
        departmentId,
        email,
        employeeNumber,
        id,
        loginName,
        mobileNumber,
        modificationDate,
        name,
        status,
        telephoneNumber
FROM ${ref("tb_day_mrd_tpd001_operators")}