config {
  type: "incremental",
  schema: "his",
  name: "tb_his_trs_tpd001_changedetails",
  uniqueKey: ["id"],
  description: "Tabela de incidentes tipada e persistida via Merge Incremental",
  bigquery: {
    partitionBy: "DATE(creationDate)",
  },
  tags: ["topdesk"],
}


SELECT 
  archivingReasonId,
  assetId,
  briefDescription,
  changeNumber,
  DATETIME(SAFE_CAST(`creationDate` AS TIMESTAMP), "America/Sao_Paulo") AS creationDate,
  externalNumber,
  id,
  requesterName
FROM ${ref("tb_day_trs_tpd001_changedetails")}
