config {
  type: "incremental",
  schema: "his",
  name: "tb_his_trs_tmb001_com_tranmt",
  description: "Tabela tb_his_trs_tmb001_com_tranmt",
  uniqueKey: ["ctm_id"],
  bigquery: {
    partitionBy: "DATE(ctm_datetime_tz)",
  },
  tags: ["commercial"],
}


SELECT 
    *
 FROM 
--   `prd-autopass-ed-001.his.tb_his_trs_tmb001_com_tranmt`
--  FOR SYSTEM_TIME AS OF TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 2 HOUR);
 
 ${ref("tb_day_trs_tmb001_com_tranmt")}