config {
  type: "incremental",
  schema: "his",
  name: "tb_his_trs_tmb001_com_tranmt_x_payment_mode",
  tags: ["commercial"],
  description: "Tabela de incidentes tipada e persistida via Merge Incremental",
  uniqueKey: ["ctmxcpm_id"],
  bigquery: {
    partitionBy: "DATE(ctmxcpm_dtpayment)",
  },

}

SELECT 
    *
 FROM prd-autopass-ed-001.his.tb_his_trs_tmb001_com_tranmt_x_payment_mode

 FOR SYSTEM_TIME AS OF TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 2 HOUR)
 --`prd-autopass-ed-001.his.tb_his_trs_tmb001_com_tranmt_x_payment_mode`
  --${ref("tb_day_trs_tmb001_com_tranmt_x_payment_mode")}