config {
    type: "table",
    schema: "day",
    name: "tb_day_mrd_tmb001_toline",
    tags: ["commercial"],
    description: "Lista de assets ATM do TOPdesk"
}

SELECT
    id,
    description,
    shortDesc,
    toTransportAuthorityId,
    isActive,
    blameUser,
    SAFE_CAST(createdAt AS DATETIME) AS createdAt,
    SAFE_CAST(updatedAt AS DATETIME) AS updatedAt,
    externalId,
    validatorDisplayText,
    farDiscountId,
    farRuleId,
    toLineDetailTypeCode,
    toLineRangeCode,
    toLineTypeCode,
    farIntegrationLineGroupId,
    farSecondaryRuleId,
    farRemunerationRuleId,
    "TMB001" AS origem,
    CURRENT_TIMESTAMP() AS dt_processamento,
    SESSION_USER() AS usuario_processamento
FROM
    ${ref("tb_ext_mrd_tmb001_toline")}
