config {
  type: "table",
  schema: "day",
  name: "tb_day_mrd_tmb001_clr_consortium",
  tags: ["tmb001"],
  description: "Lista de assets ATM do TOPdesk"
}

SELECT
    cc_id,
    cc_desc,
    DATETIME(CAST(cc_createdat_tz AS TIMESTAMP), "America/Sao_Paulo") AS cc_createdat_tz,
    DATETIME(CAST(cc_updatedat_tz AS TIMESTAMP), "America/Sao_Paulo") AS cc_updatedat_tz,
    cc_blameuser,
    "TMB001" AS origem,
    CURRENT_TIMESTAMP() AS dt_processamento,
    SESSION_USER() AS usuario_processamento
FROM
    ${ref("tb_ext_mrd_tmb001_clr_consortium")}