config {
    type: "table",
    schema: "day",
    name: "tb_day_mrd_tmb001_toline",
    tags: ["commercial"],
    description: "Lista de assets ATM do TOPdesk"
}

SELECT
    REGEXP_REPLACE(id, r'\.0$', '')                          AS id,
    description,
    shortDesc,
    REGEXP_REPLACE(toTransportAuthorityId, r'\.0$', '')      AS toTransportAuthorityId,
    isActive,
    blameUser,
    SAFE_CAST(createdAt AS DATETIME) AS createdAt,
    SAFE_CAST(updatedAt AS DATETIME) AS updatedAt,
    REGEXP_REPLACE(externalId, r'\.0$', '')                  AS externalId,
    validatorDisplayText,
    REGEXP_REPLACE(farDiscountId, r'\.0$', '')               AS farDiscountId,
    REGEXP_REPLACE(farRuleId, r'\.0$', '')                   AS farRuleId,
    toLineDetailTypeCode,
    toLineRangeCode,
    toLineTypeCode,
    REGEXP_REPLACE(farIntegrationLineGroupId, r'\.0$', '')   AS farIntegrationLineGroupId,
    REGEXP_REPLACE(farSecondaryRuleId, r'\.0$', '')          AS farSecondaryRuleId,
    REGEXP_REPLACE(farRemunerationRuleId, r'\.0$', '')       AS farRemunerationRuleId,
    "TMB001" AS origem,
    CURRENT_TIMESTAMP() AS dt_processamento,
    SESSION_USER() AS usuario_processamento
FROM
    ${ref("tb_ext_mrd_tmb001_toline")}
