config {
    type: "table",
    schema: "itg",
    name: "tb_itg_trs_tmb001_r0109_sale_app_debit",
    tags: ["commercial"],
    description: "",
    bigquery: {
        partitionBy: "dt_transaction"
    }
}
 WITH R0109 AS (select dd.tu_code 																						as cod_terminal			,
       ctm_datetime_tz 			as data_hora_trans		,
       date(ct.ctm_datetime_tz) 				as data_trans			,
       time(ctm_datetime_tz) 				as hora_trans			,
       ctd.ctm_value					as valor				,
       ctd.ctm_receivedvalue   as quantidade			,
       ctd.ctm_value*ctd.ctm_receivedvalue 	as valor_total			,
       cpm.cpm_desc 																					as forma_pagamento		,
       ctxpm.ctmxcpm_acquirer_name 																		as acquirer_name		,
       ctxpm.ctmxcpm_brand 																				as bandeira				,
       ctxpm.ctmxcpm_nsu_acquirer 																		as Id_Transacao_Cielo		,
       ctxpm.ctmxcpm_aut_acquirer 																		as cod_aprov_adquirente	,
       ctxpm.ctmxcpm_pix_txid 																			as pix_tx_id			,
       ctxpm.ctmxcpm_pix_endtoendid 																	as pix_end_to_end		,
       case
			when cp.cpt_id = '5' THEN 'BU' 
            else 'TOP' 
       end 																								as tipo_produto			,
       cp.cp_id 																						as codigo_produto		,
       cp.cp_desc 																						as produto				,
       mtp.code 																						as aplicacao			,
       ct.ctm_id 																						as idtrn				,
       cts.cts_shortdesc																				as status_orbi
  FROM prd-autopass-ed-001.his.tb_his_trs_tmb001_com_tranmt ct
 inner join prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_merchant cm ON cm.cm_id = ct.cm_id
 inner join prd-autopass-ed-001.his.tb_his_trs_tmb001_com_trandt ctd ON ctd.ctm_id = ct.ctm_id
 inner join prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_product cp ON cp.cp_id = ctd.cp_id
 inner join prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_product_type cpt ON cpt.cpt_id = cp.cpt_id
  LEFT JOIN prd-autopass-ed-001.his.tb_his_mrd_tmb001_medtransitproduct mtp ON mtp.description = cp.cp_desc 
 inner join prd-autopass-ed-001.his.tb_his_trs_tmb001_com_tranmt_x_payment_mode ctxpm ON ctxpm.ctm_id = ct.ctm_id
 inner join prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_payment_mode cpm ON cpm.cpm_id = ctxpm.cpm_id
 inner join prd-autopass-ed-001.his.tb_his_mrd_tmb001_dvc_device dd ON dd.dv_id = ct.dv_id
 inner join prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_tran_status cts on ct.ctm_status = cts.cts_id
 where ct.cm_id = '4'
   and dd.dt_id = '6'
   and ctxpm.cpm_id = '2'
   and cts.cts_id in ('A', 'P', 'V')
   and coalesce(ctxpm.ptr_id, '0') > '0'
   and ct.ctm_datetime_tz >= '2025-01-01'
)

select 
    idtrn		cd_transaction		,
    Id_Transacao_Cielo	cd_transaction_cielo	,
    cod_terminal	cd_pos_device		,
    data_hora_trans	 dh_transaction	,
    data_trans	dt_transaction	,
    hora_trans		tm_transaction	,
    upper(tipo_produto)	 ds_product_type		,
    codigo_produto	 cd_product_type	,
    upper(produto)		 ds_product		,
    aplicacao		 cd_product	,				
    cod_aprov_adquirente  cd_acquirer_authorization	,
    pix_tx_id		 ds_pix_tx	,
    pix_end_to_end	 ds_pix_end_to_end	,
    upper(acquirer_name)	 ds_acquirer	,
    upper(bandeira) ds_card_brand ,
    quantidade	qt_transaction		,
    valor	 vl_transaction		,
     valor_total vl_total		,
     CURRENT_TIMESTAMP() ts_processing,
    'AUT001' cd_company,
    CAST(FORMAT_TIMESTAMP("%Y%m%d%H%M%S", CURRENT_TIMESTAMP()) AS INT64) nr_load_control,
    SESSION_USER() cd_created_by,
    'TMB001' cd_system_source	
from R0109