config {
    type: "table",
    schema: "itg",
    description: "",
    tags: ["treport"],
    bigquery: {
        partitionBy: "dt_transaction",
    }
}

 -- R0108
WITH
  R0108 AS (
  SELECT
    dd.tu_code AS cod_terminal,
    DATE(pp.ppx_paymentdate) AS data_trans, 
    TIME(pp.ppx_paymentdate) AS hora_trans,
    --DATE(TIMESTAMP(ct.ctm_datetime_tz, 'UTC'), 'America/Sao_Paulo') AS data_trans,
    --TIME(TIMESTAMP(ct.ctm_datetime_tz, 'UTC'), 'America/Sao_Paulo') hora_trans,
    --REPLACE(FORMAT('%.2f', ctd.ctm_value), '.',',') AS valor,
    ctd.ctm_value AS valor,
    ctd.ctm_receivedvalue AS quantidade,
    -- REPLACE(FORMAT('%.2f', ctd.ctm_value * ctd.ctm_receivedvalue), '.',',') valor_total,
    --ctd.ctm_value * ctd.ctm_receivedvalue AS valor_total,
    ct.ctm_receivedvalue                                                             AS valor_total,
    cpm.cpm_desc AS forma_pagamento,
    -- ctxpm.ctmxcpm_acquirer_name 																		as acquirer_name		,
    -- ctxpm.ctmxcpm_brand 																				as bandeira				,
    ctxpm.ctmxcpm_nsu_acquirer AS nsu_adquirente,
    -- ctxpm.ctmxcpm_aut_acquirer 																		as cod_aprov_adquirente	,
    ctxpm.ctmxcpm_pix_txid AS pix_tx_id,
    ctxpm.ctmxcpm_pix_endtoendid AS pix_end_to_end,
    CASE
      WHEN cp.cpt_id = '5' THEN 'BU'
      ELSE 'TOP'
  END
    AS tipo_produto,
    cp.cp_id AS codigo_produto,
    cp.cp_desc AS produto,
    mtp.code AS aplicacao,
    ct.ctm_id AS idtrn,
    ct.ctm_status AS status_orbi,
    ct.ctt_id,
    CASE ctxpm.ctmxcpm_status
      WHEN 'C' THEN 'Conciliado'
      WHEN 'D' THEN 'Divergência valor'
      ELSE 'Não conciliado'
  END
    AS conciliacao
  FROM
    prd-autopass-ed-001.his.tb_his_trs_tmb001_com_tranmt ct
  INNER JOIN
    prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_merchant cm ON cm.cm_id = ct.cm_id
  INNER JOIN
    prd-autopass-ed-001.his.tb_his_trs_tmb001_com_trandt ctd ON ctd.ctm_id = ct.ctm_id
  INNER JOIN
    prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_product cp ON cp.cp_id = ctd.cp_id
  INNER JOIN
    prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_product_type cpt ON cpt.cpt_id = cp.cpt_id
  LEFT JOIN
    prd-autopass-ed-001.his.tb_his_mrd_tmb001_medtransitproduct mtp ON mtp.description = cp.cp_desc
  INNER JOIN
    `prd-autopass-ed-001.his.tb_his_trs_tmb001_com_tranmt_x_payment_mode` ctxpm ON ctxpm.ctm_id = ct.ctm_id
    AND ctxpm.cpm_id = '5'
  INNER JOIN
    prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_payment_mode cpm ON cpm.cpm_id = ctxpm.cpm_id
  INNER JOIN
    prd-autopass-ed-001.his.tb_his_mrd_tmb001_dvc_device dd ON dd.dv_id = ct.dv_id
  inner JOIN `prd-autopass-ed-001.his.tb_his_trs_tmb001_pay_pix` pp on ctxpm.ptr_id = pp.ptr_id
  WHERE
    ct.cm_id = '4'
   -- AND ct.ctt_id IN ('1','2')
   -- AND dd.dt_id = '6'
    AND ct.ctm_status IN ('A','P') 
     -- and pp.ppx_paymentdate >= '2025-01-01'
      )


SELECT 
    idtrn cd_transaction,
    ctt_id cd_com_transaction,
    cod_terminal cd_pos_device,
    data_trans dt_transaction,
    hora_trans tm_transaction,
    codigo_produto cd_product_type,
    upper(tipo_produto) ds_product_type,
    aplicacao cd_product,
    upper(produto) ds_product,
    pix_tx_id ds_pix_tx,
    pix_end_to_end ds_pix_end_to_end,
    forma_pagamento ds_payment_mode,
    nsu_adquirente nr_nsu_acquirer,
    upper(status_orbi) ds_status,
    upper(conciliacao) ds_conciliation,
    quantidade qt_transaction,
    valor vl_transaction,
    valor_total vl_total,
    CURRENT_TIMESTAMP() ts_processing,
    'AUT001' cd_company,
    CAST(FORMAT_TIMESTAMP("%Y%m%d%H%M%S", CURRENT_TIMESTAMP()) AS INT64) nr_load_control,
    SESSION_USER() cd_created_by,
    'TMB001' cd_system_source
  FROM
    R0108
     WHERE data_trans >= '2025-01-01'
