config {
    type: "table",
    schema: "itg",
    description: "",
    tags: ["commercial"],
    bigquery: {
        partitionBy: "dt_transaction",
    }
}

  --R0060
WITH
  R0060 AS (
  SELECT
    cod_terminal,
    DATE(data_hora_trans) AS data_trans,
    TIME(data_hora_trans) AS hora_trans,
    --DATE(TIMESTAMP(data_hora_trans, 'UTC'), 'America/Sao_Paulo') AS data_trans2,
    --TIME(TIMESTAMP(data_hora_trans, 'UTC'), 'America/Sao_Paulo') hora_trans2,
    valor,
    quantidade,
    valor_total,
    forma_pagamento,
    acquirer_name,
    bandeira,
    nsu_adquirente,
    cod_aprov_adquirente,
    pix_tx_id,
    pix_end_to_end,
    tipo_produto,
    codigo_produto,
    produto,
    aplicacao,
    idtrn,
    CASE
      WHEN status_orbi = 'A' THEN 'Ativo'
      WHEN status_orbi = 'P' THEN 'Pendente'
      WHEN status_orbi = 'I' THEN 'Inativo'
      ELSE status_orbi
  END
    status_orbi,
    conciliacao
  FROM (
    SELECT
      dd.tu_code AS cod_terminal,
      ct.ctm_datetime_tz AS data_hora_trans,
      ctd.ctm_value AS valor,
      ctd.ctm_receivedvalue AS quantidade,
      ctd.ctm_value * ctd.ctm_receivedvalue AS valor_total,
      ctxpm.ctmxcpm_nsu_acquirer AS nsu_adquirente,
      ctxpm.ctmxcpm_aut_acquirer AS cod_aprov_adquirente,
      CASE
        WHEN cp.cpt_id = '5' THEN 'BU'
        ELSE 'TOP'
    END
      AS tipo_produto,
      cp.cp_id AS codigo_produto,
      cp.cp_desc AS produto,
      mtp.code AS aplicacao,
      ct.ctm_id AS idtrn,
      ct.ctm_status AS status_orbi,
      cpm.cpm_desc AS forma_pagamento,
      ctxpm.ctmxcpm_pix_txid AS pix_tx_id,
      ctxpm.ctmxcpm_pix_endtoendid AS pix_end_to_end,
      ctxpm.ctmxcpm_acquirer_name AS acquirer_name,
      ctxpm.ctmxcpm_brand AS bandeira,
      CASE ctxpm.ctmxcpm_status
        WHEN 'C' THEN 'Conciliado'
        WHEN 'D' THEN 'Divergência valor'
        ELSE 'Não conciliado'
    END
      AS conciliacao
    FROM
      prd-autopass-ed-001.his.tb_his_trs_tmb001_com_tranmt ct
    JOIN
      prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_merchant cm
    ON
      cm.cm_id = ct.cm_id
    LEFT JOIN
      prd-autopass-ed-001.his.tb_his_trs_tmb001_com_trandt ctd
    ON
      ctd.ctm_id = ct.ctm_id
    LEFT JOIN
      prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_product cp
    ON
      cp.cp_id = ctd.cp_id
    LEFT JOIN
      prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_product_type cpt
    ON
      cpt.cpt_id = cp.cpt_id
    LEFT JOIN
      prd-autopass-ed-001.his.tb_his_mrd_tmb001_medtransitproduct mtp
    ON
      mtp.description = cp.cp_desc
    JOIN
      prd-autopass-ed-001.his.tb_his_trs_tmb001_com_tranmt_x_payment_mode ctxpm
    ON
      ctxpm.ctm_id = ct.ctm_id
      AND ctxpm.cpm_id = '5'
    LEFT JOIN
      prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_payment_mode cpm
    ON
      cpm.cpm_id = ctxpm.cpm_id
    LEFT JOIN
      prd-autopass-ed-001.his.tb_his_mrd_tmb001_dvc_device dd
    ON
      dd.dv_id = ct.dv_id
    LEFT JOIN
      prd-autopass-ed-001.his.tb_his_mrd_tmb001_toterminal tt
    ON
      tt.code = dd.tu_code
      AND tt.toTransportOperatorId = cm.cm_organization_id
    WHERE
      ct.ctt_id = '2'
      AND ct.cm_id = '20' ) sel )
      
  SELECT
    idtrn cd_transaction,
    cod_terminal cd_pos_device,
    data_trans dt_transaction,
    hora_trans tm_transaction,
    codigo_produto cd_product_type,
    upper(tipo_produto) ds_product_type,
    aplicacao cd_product,
    upper(produto) ds_product,
    pix_tx_id ds_pix_tx,
    pix_end_to_end ds_pix_end_to_end,
    forma_pagamento ds_payment_mode,
    upper(bandeira) ds_card_network,
    upper(acquirer_name) ds_acquirer,
    nsu_adquirente nr_nsu_acquirer,
    cod_aprov_adquirente  cd_acquirer_authorization,
    upper(status_orbi) ds_status,
    upper(conciliacao) ds_conciliation,
    quantidade qt_transaction,
    valor vl_transaction,
    valor_total vl_total,
    CURRENT_TIMESTAMP() ts_processing,
    'AUT001' cd_company,
    CAST(FORMAT_TIMESTAMP("%Y%m%d%H%M%S", CURRENT_TIMESTAMP()) AS INT64) nr_load_control,
    SESSION_USER() cd_created_by,
    'TMB001' cd_system_source
  FROM
    R0060
    where 
    data_trans  >= '2025-01-01'