config {
    type: "table", 
    schema: "dfl",
    tags: ['dfl'],
    description: "Tabela itg de vendas por cartão ",
    bigquery: {
        partitionBy: "dt_transaction",
    }
}



SELECT 
   cd_pos_device,
   dt_transaction ,
   dt_transaction_pkm ,
   fl_bolsao,
   dt_operation ,

   ds_empresa,
   ds_linha_completa,
   ds_linha,
   ds_estacao_origem,
   ds_estacao,
   ds_estacao_sigla,


--JA NÃO USADA ESTA VINDO DO DEPARAS TABELAS SHAREPOINT
--    nm_company ,
--    nm_line ,
--    nm_line_agg ,
--    nm_station ,
--    nm_station_agg ,
   ds_status_sale ,
   ds_pos_device ,
   ds_device_type ,
   ds_product ,
   ds_product_agg ,    
   ds_payment_mode ,
   nm_acquirer,  
   COUNT(cd_qrcode_media) qt_ticket,
   COUNT(DISTINCT cd_transaction) qt_sale,
   SUM(vl_transaction) vl_sale,
   CURRENT_TIMESTAMP() ts_processing,
   cd_company cd_company,
   CAST(FORMAT_TIMESTAMP("%Y%m%d%H%M%S", CURRENT_TIMESTAMP()) AS INT64) nr_load_control,
   SESSION_USER() cd_created_by,
   cd_system_source cd_system_source
 FROM   ${ref("tb_itg_trs_top001_qrcode_sale")}
 --`dev-autopass-bi-001.dfl.tb_itg_trs_top001_qrcode_sale` qs
 --itg.tb_itg_trs_top001_qrcode_sale qs
 WHERE ds_short_record_status_transaction <> 'SH2000'
-- AND dt_transaction >= date_sub(DATE_TRUNC(CURRENT_DATE(), MONTH), interval 2 year)
 GROUP BY ALL