config {
    type: "incremental",
    schema: "his",
    name: "his_com_tranmt",
    tags: ["tmob"],
    bigquery: {
        partitionBy: "DATE(ctm_datetime_br)",
        clusterBy: ["cm_id", "ctm_status", "cs_id"] ,
        updatePartitionFilter: "ctm_datetime_br >= timestamp_sub(current_timestamp(), interval 180 day)"

    },
    description: "Tabela histórica de todas as transações no tmob"
}

-- 1. Preparação dos dados de entrada (Carga Full ou Incremental)
WITH raw_data AS (
    SELECT 
        ctm_id,
        cm_id,
        ctt_id,
        cs_id,
        dv_id,
        ctm_status,
        ctm_datetime_tz,
        ctm_confirm_datetime_tz,
        ctm_externalid,
        ctm_createdat,
        ctm_updatedat,
        ctm_createdby,
        ctm_updatedby,
        ctm_tef_receipt,
        ctm_legacy_id,
        SAFE_CAST(ctm_value AS NUMERIC) as ctm_value_num,
        SAFE_CAST(ctm_receivedvalue AS NUMERIC) as ctm_receivedvalue_num,
        DATETIME(TIMESTAMP(ctm_datetime_tz), 'America/Sao_Paulo') as ctm_datetime_br
    FROM  `dev-autopass-bi-001.temp.day_com_tranmt`
    
    `dev-autopass-bi-001.temp.ext_com_tranmt` 
    --${ref("ext_com_tranmt")}
        
-- teste
)

select * from raw_data