config {
    type: "incremental",
    schema: "his",
    name: "his_com_tranmt",
    tags: ["tmob"],
    uniqueKey: ["ctm_id"], 
    bigquery: {
        partitionBy: "DATE(ctm_datetime_br)",
        clusterBy: ["cm_id", "ctm_status", "cs_id"],
        updatePartitionFilter: "ctm_datetime_br >= DATE_SUB(CURRENT_DATE('America/Sao_Paulo'), INTERVAL 180 DAY)"
    },
    description: "Tabela histórica de todas as transações no tmob"
}

WITH raw_data AS (
    SELECT
        ctm_id,
        cm_id,
        ctt_id,
        cs_id,
        dv_id,
        ctm_status,
        ctm_datetime_tz,
        ctm_confirm_datetime_tz,
        ctm_externalid,
        ctm_createdat,
        ctm_updatedat,
        ctm_createdby,
        ctm_updatedby,
        ctm_tef_receipt,
        ctm_legacy_id,
        ctm_value,
        ctm_receivedvalue,
        ctm_datetime_br,
        CURRENT_TIMESTAMP() AS dataform_updated_at
    FROM  
            ${ref("bronze_com_tranmt")}
    WHERE ctm_id IS NOT NULL
)

SELECT 
    *
    
FROM raw_data

${when(incremental(), `
    WHERE 
        -- Filtro usando o SELF para pegar apenas o que é mais novo que o máximo da história
        TIMESTAMP(ctm_datetime_tz) > (SELECT COALESCE(MAX(TIMESTAMP(ctm_datetime_tz)), TIMESTAMP('1900-01-01')) FROM ${self()})
        OR TIMESTAMP(ctm_createdat) > (SELECT COALESCE(MAX(TIMESTAMP(ctm_createdat)), TIMESTAMP('1900-01-01')) FROM ${self()})
        OR TIMESTAMP(ctm_updatedat) > (SELECT COALESCE(MAX(TIMESTAMP(ctm_updatedat)), TIMESTAMP('1900-01-01')) FROM ${self()})
`)}

--Garante que o lote de entrada não tenha duplicados
QUALIFY ROW_NUMBER() OVER(PARTITION BY ctm_id ORDER BY ctm_updatedat DESC, ctm_datetime_tz DESC) = 1