config {
    type: "table", // Criamos como tabela para ter os dados fisicamente no BQ
    schema: "tmp",
    name: "incidentprocessingstatuses_all_text",
    description: "Camada Bronze: Dados persistidos como texto para garantir resiliência contra mudanças de schema",
    tags: ["topdesk"],
}


SELECT 
    archive,
    id,
    name,
    `order`
FROM `dev-autopass-bi-001.tmp.ext_incidentprocessingstatuses`