config {
  type: "table",
  schema: "day",
  name: "tb_day_mrd_tmb001_usruser",
  tags: ["commercial"],

  
}
SELECT
  REGEXP_REPLACE(id,                                r'\.0$', '') AS id,
  name                                          AS name,
  socialName                                    AS socialName,
  SAFE_CAST(birthdate AS DATE)                  AS birthdate,
  gender                                        AS gender,
  motherName                                    AS motherName,
  fatherName                                    AS fatherName,
  mailAddress                                   AS mailAddress,
  REGEXP_REPLACE(usrMainDocumentId,                 r'\.0$', '') AS usrMainDocumentId,
  REGEXP_REPLACE(usrMainPhoneId,                    r'\.0$', '') AS usrMainPhoneId,
  REGEXP_REPLACE(usrMainAddressId,                  r'\.0$', '') AS usrMainAddressId,
  isActive                                      AS isActive,
  blameUser                                     AS blameUser,
  SAFE_CAST(createdAt AS TIMESTAMP)             AS createdAt,
  SAFE_CAST(updatedAt AS TIMESTAMP)             AS updatedAt,
  `hash`,                                         
  REGEXP_REPLACE(usrMainPhotoId,                    r'\.0$', '') AS usrMainPhotoId,
  aggregatedData                                AS aggregatedData,
  isOperator                                    AS isOperator,
  REGEXP_REPLACE(externalId,                        r'\.0$', '') AS externalId,
  REGEXP_REPLACE(legacyId,                          r'\.0$', '') AS legacyId,
  filiation1                                    AS filiation1,
  filiation2                                    AS filiation2,
  isLocked                                      AS isLocked,
  SAFE_CAST(statusCheckDate AS TIMESTAMP)       AS statusCheckDate,
  usrStatusCode                                 AS usrStatusCode,
  REGEXP_REPLACE(usrMainCommentId,                  r'\.0$', '') AS usrMainCommentId,
  paymentSecret                                 AS paymentSecret,
  nationality                                   AS nationality,
  maritalStatus                                 AS maritalStatus,
  SAFE_CAST(familyIncome AS NUMERIC)            AS familyIncome,
  SAFE_CAST(personalIncome AS NUMERIC)          AS personalIncome,
  responsible                                   AS responsible,

  "TMB001" AS origem,
  CURRENT_TIMESTAMP() AS dt_processamento,
  SESSION_USER() AS usuario_processamento

FROM ${ref("tb_ext_mrd_tmb001_usr_user")}

