config {
    type: "table",
    schema: "day",
    name: "tb_day_mrd_tmb001_pay_voucher_type",
    tags: ["commercial"],
    description: "Tabela pay_voucher_type tipada — tipos de voucher"
}

SELECT
    REGEXP_REPLACE(pvt_id, r'\.0$', '') AS pvt_id,
    pvt_desc,
    DATETIME(CAST(pvt_createdat AS TIMESTAMP), 'America/Sao_Paulo') AS pvt_createdat,
    pvt_createdby,
    DATETIME(CAST(pvt_updatedat AS TIMESTAMP), 'America/Sao_Paulo') AS pvt_updatedat,
    pvt_updatedby,

    "TMB001" AS origem,
    CURRENT_TIMESTAMP() AS dt_processamento,
    SESSION_USER() AS usuario_processamento

FROM ${ref("tb_ext_mrd_tmb001_pay_voucher_type")}