config {
  type: "table",
  schema: "day",
  name: "tb_day_mrd_tmb001_medmedia",
  tags: ["commercial"],
  
}

SELECT
  REGEXP_REPLACE(id,                                r'\.0$', '') AS id,
  SAFE_CAST(sequence AS NUMERIC)                  AS sequence,
  checkDig                                        AS checkDig,
  formatedLogical                                 AS formatedLogical,
  isProcessed                                     AS isProcessed,
  csn                                              AS csn,
  isCsnExtended                                   AS isCsnExtended,
  SAFE_CAST(sizeInKB AS NUMERIC)                  AS sizeInKB,
  tagType                                         AS tagType,
  REGEXP_REPLACE(medMediaTypeId,                    r'\.0$', '') AS medMediaTypeId,
  blameUser                                       AS blameUser,
  SAFE_CAST(createdAt AS TIMESTAMP)               AS createdAt,
  SAFE_CAST(updatedAt AS TIMESTAMP)               AS updatedAt,
  isActive                                        AS isActive,
  isHotlisted                                     AS isHotlisted,
  SAFE_CAST(recordDate AS TIMESTAMP)              AS recordDate,
  usrUserHash                                     AS usrUserHash,
  REGEXP_REPLACE(usrUserId,                         r'\.0$', '') AS usrUserId,
  REGEXP_REPLACE(usrOrganizationId,                 r'\.0$', '') AS usrOrganizationId,
  SAFE_CAST(reissueSequence AS NUMERIC)           AS reissueSequence,
  toIssuerCode                                    AS toIssuerCode,
  REGEXP_REPLACE(activePersoOrderId,                r'\.0$', '') AS activePersoOrderId,
  usrTypeIds                                      AS usrTypeIds,
  REGEXP_REPLACE(medMediaReissueFromId,             r'\.0$', '') AS medMediaReissueFromId,
  REGEXP_REPLACE(externalId,                        r'\.0$', '') AS externalId,
  toSysCode                                       AS toSysCode,
  bss_id                                          AS bss_id,
  REGEXP_REPLACE(medMediaTemplateId,                r'\.0$', '') AS medMediaTemplateId,
  REGEXP_REPLACE(paymentTransactionId,              r'\.0$', '') AS paymentTransactionId,
  SAFE_CAST(receiveddate_tz AS TIMESTAMP)         AS receiveddate_tz,
  receivedby                                      AS receivedby,
  mediadf                                         AS mediadf,

  "TMB001" AS origem,
  CURRENT_TIMESTAMP() AS dt_processamento,
  SESSION_USER() AS usuario_processamento

FROM ${ref("tb_ext_mrd_tmb001_med_media")}