config {
    type: "table",
    schema: "his",
    tags: ["shp001"],
    description: "Tabela de-para de mapeamento de estação",
    columns: {
        cd_origem: "Código identificador do sistema de origem (Ex: TOP, TMB)",
        cd_estacao: "Número identificador da estação",
        ds_estacao: "Descrição da estação ajustada",
        ds_estacao_origem: "Descrição da estação sem tratamento"
    }
}

select 
'TOP' cd_origem,
ld.cd_line_detail cd_estacao, ld.ds_long ds_estacao_origem, 
CASE
    WHEN cd_line_detail = '905' THEN 'AACD SERVIDOR'
    WHEN cd_line_detail = '912' THEN 'ADOLFO PINHEIRO'
    WHEN cd_line_detail = '913' THEN 'ALTO DA BOA VISTA'
    WHEN cd_line_detail = '71'  THEN 'ALTO DO IPIRANGA'
    WHEN cd_line_detail = '62'  THEN 'ANA ROSA'
    WHEN cd_line_detail = '76'  THEN 'ANHANGABAU'
    WHEN cd_line_detail = '37'  THEN 'ARTUR ALVIM'
    WHEN cd_line_detail = '102' THEN 'PALMEIRAS BARRA FUNDA'
    WHEN cd_line_detail = '67'  THEN 'BELEM'
    WHEN cd_line_detail = '914' THEN 'BORBA GATO'
    WHEN cd_line_detail = '69'  THEN 'BRAS'
    WHEN cd_line_detail = '68'  THEN 'BRESSER MOOCA'
    WHEN cd_line_detail = '57'  THEN 'BRIGADEIRO'
    WHEN cd_line_detail = '915' THEN 'BROOKLIN'
    WHEN cd_line_detail = '922' THEN 'BUTANTA'
    WHEN cd_line_detail IN ('917','203') THEN 'CAMPO BELO'
    WHEN cd_line_detail = '910' THEN 'CAMPO LIMPO'
    WHEN cd_line_detail = '911' THEN 'CAPAO REDONDO'
    WHEN cd_line_detail = '59'  THEN 'CARRAO'
    WHEN cd_line_detail IN ('903','65') THEN 'CHACARA KLABIN'
    WHEN cd_line_detail = '46'  THEN 'CLINICAS'
    WHEN cd_line_detail = '52'  THEN 'CONSOLACAO'
    WHEN cd_line_detail = '3'   THEN 'CORINTHIANS ITAQUERA'
    WHEN cd_line_detail = '916' THEN 'EUCALIPTOS'
    WHEN cd_line_detail = '921' THEN 'FARIA LIMA'
    WHEN cd_line_detail = '120' THEN 'FAZENDA DA JUTA'
    WHEN cd_line_detail = '925' THEN 'FRADIQUE COUTINHO'
    WHEN cd_line_detail = '908' THEN 'GIOVANNI GRONCHI'
    WHEN cd_line_detail = '40'  THEN 'GUILHERMINA ESPERANCA'
    WHEN cd_line_detail = '923' THEN 'HIGIENOPOLIS MACKENZIE'
    WHEN cd_line_detail = '5'   THEN 'HOSPITAL SAO PAULO'
    WHEN cd_line_detail = '134' THEN 'JARDIM COLONIAL'
    WHEN cd_line_detail = '906' THEN 'LARGO TREZE'
    WHEN cd_line_detail IN ('28','924') THEN 'LUZ'
    WHEN cd_line_detail = '98'  THEN 'MARECHAL DEODORO'
    WHEN cd_line_detail = '904' THEN 'MOEMA'
    WHEN cd_line_detail = '926' THEN 'OSCAR FREIRE'
    WHEN cd_line_detail = '60'  THEN 'PARAISO'
    WHEN cd_line_detail = '39'  THEN 'PATRIARCA'
    WHEN cd_line_detail = '920' THEN 'PAULISTA'
    WHEN cd_line_detail = '74'  THEN 'PEDRO II'
    WHEN cd_line_detail = '53'  THEN 'PENHA'
    WHEN cd_line_detail = '919' THEN 'PINHEIROS'
    WHEN cd_line_detail = '26'  THEN 'SE'
    WHEN cd_line_detail = '78'  THEN 'REPUBLICA'
    WHEN cd_line_detail = '72'  THEN 'SACOMA'
    WHEN cd_line_detail = '81'  THEN 'SANTA CECILIA'
    WHEN cd_line_detail IN ('21','902') THEN 'SANTA CRUZ'
    WHEN cd_line_detail = '907' THEN 'SANTO AMARO'
    WHEN cd_line_detail = '132' THEN 'SAO MATEUS'
    WHEN cd_line_detail IN ('4','195') THEN 'SAO PAULO MORUMBI'
    WHEN cd_line_detail = '16'  THEN 'SUMARE'
    WHEN cd_line_detail = '73'  THEN 'TAMANDUATEI'
    WHEN cd_line_detail = '63'  THEN 'TATUAPE'
    WHEN cd_line_detail = '31'  THEN 'PORTUGUESA TIETE'
    WHEN cd_line_detail = '56'  THEN 'TRIANON MASP'
    WHEN cd_line_detail = '909' THEN 'VILA DAS BELEZAS'
    WHEN cd_line_detail = '2'   THEN 'VILA MADALENA'
    WHEN cd_line_detail = '51'  THEN 'VILA MATILDE'
    WHEN cd_line_detail IN ('15','75') THEN 'VILA PRUDENTE'
    WHEN cd_line_detail = '918' THEN 'VILA SONIA'
    WHEN cd_line_detail = '114' THEN 'VILA TOLSTOI'
    ELSE ld.ds_long
END AS ds_estacao
from prd-autopass-bi-001.his.tb_his_mrd_top001_line_detail ld
JOIN prd-autopass-bi-001.his.tb_his_mrd_top001_line lm
ON ld.cd_line = lm.cd_line
where cd_location in ('METRO', 'CPTM')
UNION ALL
SELECT 'BOM' cd_origem,ld.cd_line_detail cd_estacao, ld.ds_long ds_estacao_origem, 
CASE ld.cd_line_detail
    WHEN '13400' THEN 'LUZ'
    WHEN '12301' THEN 'VILA PRUDENTE'
    WHEN '12300' THEN 'IPIRANGA'
    WHEN '12308' THEN 'SAPOPEMBA'
    WHEN '12317' THEN 'HOSPITAL CIDADE TIRADENTES'
    WHEN '12302' THEN 'ORATORIO'
    WHEN '12303' THEN 'SAO LUCAS'
    WHEN '12315' THEN 'MARCIO BECK'
    WHEN '12305' THEN 'VILA TOSTOI'
    WHEN '12316' THEN 'CIDADE TIRADENTES'
    WHEN '12313' THEN 'JACU-PESSEGO'
    WHEN '12309' THEN 'FAZENDA JUTA'
    WHEN '12314' THEN 'ERICO SEMER'
    WHEN '12304' THEN 'CAMILO HADDAD'
    WHEN '12307' THEN 'JARDIM PLANALTO'
    WHEN '12306' THEN 'VILA UNIAO'
    WHEN '12310' THEN 'SAO MATHEUS'
    WHEN '12311' THEN 'IGUATEMI'
    WHEN '12312' THEN 'JEQUIRICA'
    WHEN '12201' THEN 'PARADA INGLESA'
    WHEN '12056' THEN 'ADOLFO PINHEIRO'
    WHEN '13401' THEN 'FARIA LIMA'
    WHEN '13402' THEN 'BUTANTA'
    WHEN '13403' THEN 'FRAD COUTINHO'
    WHEN '12059' THEN 'BROOKLIN'
    WHEN '12057' THEN 'ALTO BOA VISTA'
    WHEN '12058' THEN 'BORBA GATO'
    WHEN '13500' THEN 'ENGENHEIRO GOULART'
    WHEN '13502' THEN 'AEROPORTO - GUARULHOS'
    WHEN '13501' THEN 'GUARULHOS - CECAP'
    WHEN '13404' THEN 'HIGIENOPOLIS-MACKENZIE'
    WHEN '12061' THEN 'CAMPO BELO'
    WHEN '13117' THEN 'JOAO DIAS'
    WHEN '13017' THEN 'PALMEIRAS BARRA FUNDA'
    WHEN '13043' THEN 'QUITAUNA'
    WHEN '13047' THEN 'IMPERATRIZ LEOPOLDINA'
    WHEN '13010' THEN 'PERUS'
    WHEN '13040' THEN 'SANTA TEREZINHA'
    WHEN '13050' THEN 'BARRA FUNDA'
    ELSE ld.ds_long
END AS ds_estacao
from prd-autopass-bi-001.his.tb_his_mrd_bom001_line_detail ld
JOIN prd-autopass-bi-001.his.tb_his_mrd_bom001_line lm
ON ld.cd_line = lm.cd_line
where  lm.ds_short in ('VERMELHA', 'VERDE', 'TURQUESA', 'SAFIRA', 'RUBI', 'PRATA', 'OURO', 'ONIX', 'LILAS', 'LARANJA', 'JADE', 'ESMERALDA', 'DIAMANTE', 'CORAL', 'AZUL', 'AMARELA' )