config {
  type: "incremental",
  schema: "his",
  name: "tb_his_trs_tmb001_app_onboardingrequest",
  tags: ["commercial"],
  description: "Tabela app_onboardingrequest tipada e persistida via Merge Incremental",
  uniqueKey: ["aor_id"],
  bigquery: {
    partitionBy: "DATE(aor_createdat)",
    clusterBy: ["aor_id"]
  }
}

SELECT * FROM ${ref("tb_day_trs_tmb001_app_onboardingrequest")}