config {
    type: "table", 
    schema: "itg",
    description: "Tabela gold para o fluxo de dados df_catracada_cartao ",
    tags: ["FORA"],
    bigquery: {
        partitionBy: "dt_card_usage",
    }
}


--fat_catracada_uso_excessivo
SELECT
'TOP' origem
, o.nr_card
,SHA256(nr_registered_number_cpf) nr_cpf_hash
,o.qt_usage
,o.dt_card_usage
,o.tm_first_usage
,o.dt_last_usage
,o.tm_last_usage
,o.ds_consortium
,o.ds_consortium_group
,o.nm_line
,o.nm_company
,o.nm_station
,o.cd_vehicle
,o.ds_line_direction
,o.cd_boarding_status
,o.ds_product
, CASE WHEN o.nm_line LIKE '%INTEGRAÇÃO%' THEN 1 ELSE 0 END fl_integracao
FROM
  `prd-autopass-bi-001.itg.vw_itg_trs_top001_card_usage_excessive` o
LEFT JOIN
    prd-autopass-bi-001.itg.tb_itg_trs_top001_card_emission a
  ON
    a.nr_card = o.nr_card
WHERE
  (1=1)
  AND o.nr_card NOT IN (
  SELECT
    a.nr_card
  FROM
    prd-autopass-bi-001.itg.vw_itg_mrd_top001_user b
  JOIN
    prd-autopass-bi-001.itg.tb_itg_trs_top001_card_emission a
  ON
    a.cd_user = b.cd_user
  WHERE
    b.nm_user LIKE 'METRA%')
UNION ALL
SELECT
'BOM' origem
,os.nr_card
,SHA256(nr_registered_number_cpf) nr_cpf_hash
,os.qt_usage
,os.dt_card_usage
,os.tm_first_usage
,os.dt_last_usage
,os.tm_last_usage
,os.ds_consortium
,os.ds_consortium_group
,os.nm_line
,os.nm_company
,os.nm_station
,os.cd_vehicle
,os.ds_line_direction
,os.cd_boarding_status
,os.ds_product
, CASE WHEN nm_line LIKE '%INTEGRAÇÃO%' THEN 1 ELSE 0 END fl_integracao
FROM
  `prd-autopass-bi-001.itg.vw_itg_trs_bom001_card_usage_excessive` os
  LEFT JOIN
    prd-autopass-bi-001.itg.tb_itg_trs_top001_card_emission a
  ON
    a.nr_card = os.nr_card
WHERE
  (1=1)
  AND os.nr_card NOT IN (
  SELECT
    a.nr_card
  FROM
    prd-autopass-bi-001.itg.vw_itg_mrd_bom001_user b
  JOIN
    prd-autopass-bi-001.itg.tb_itg_trs_bom001_card_emission a
  ON
    a.cd_user = b.cd_user
  WHERE
    b.nm_user LIKE 'METRA%')