config {
    type: "table", 
    schema: "tmp",
    description: "Tabela gold para o fluxo de dados df_emissao ",
    tags: ["powerbi_emissao"],
    bigquery: {
        partitionBy: "dt_impressao",
    }
}


WITH agrupador_produto AS (  SELECT
        'TOP' ds_origem,
        a.ts_processing,
        a.cd_system_source AS cd_origem_sistema,
        a.nr_registered_number_cpf,
        SHA256(a.nr_registered_number_cpf) AS cpf_hash,
        CONCAT(CAST(a.dt_print AS STRING), ' ', CAST(a.tm_print AS STRING)) AS dh_impressao,
        a.ds_long_remote_printer AS ds_impressora,
        a.ds_print_status AS ds_status_impressao,  
        a.cd_user_printer_card AS cd_usuario_impressao,
        a.ds_card_status AS ds_status_cartao,
        CASE
            WHEN a.ds_card_status = 'AGUARDANDO IMPRESSAO' AND a.ds_print_status = 'NAO IMPRESSO' THEN 'NAO IMPRESSO'
            WHEN a.ds_card_status = 'AGUARDANDO IMPRESSAO' AND a.ds_print_status = 'IMPRESSO' THEN 'NAO IMPRESSO'
            WHEN a.ds_card_status = 'ATIVO' AND a.ds_print_status = 'IMPRESSO' THEN 'IMPRESSO'
            WHEN a.ds_card_status = 'ATIVO' AND a.ds_print_status = 'ATIVO' THEN 'IMPRESSO'
            WHEN a.ds_card_status = 'ATIVO' AND a.ds_print_status = 'NAO IMPRESSO' THEN 'NAO IMPRESSO'
            WHEN a.ds_card_status = 'HOTLIST' AND a.ds_print_status = 'IMPRESSO' THEN 'IMPRESSO'
            WHEN a.ds_card_status = 'HOTLIST' AND a.ds_print_status = 'NAO IMPRESSO' THEN 'NAO IMPRESSO'
            WHEN a.ds_card_status = 'HOTLIST' AND a.ds_print_status = 'ATIVO' THEN 'IMPRESSO'
            WHEN a.ds_card_status = 'INATIVO' AND a.ds_print_status = 'IMPRESSO' THEN 'IMPRESSO'
            WHEN a.ds_card_status = 'INATIVO' AND a.ds_print_status = 'NAO IMPRESSO' THEN 'NAO IMPRESSO'
            WHEN a.ds_card_status = 'INATIVO' AND a.ds_print_status = 'ATIVO' THEN 'NAO IMPRESSO'
            WHEN a.ds_card_status = 'U' AND a.ds_print_status = 'ATIVO' THEN 'NAO IMPRESSO'
            ELSE 'NAO IMPRESSO' 
        END AS ds_status_simplificado, ds_status_serpro,
        CASE
            WHEN a.ds_card_design = 'TOP' THEN 'TOP' 
            WHEN a.ds_card_design = 'TOP EMV' THEN 'TOP EMV' 
            WHEN a.ds_card_design = 'OPERACIONAL' THEN 'OPERACIONAL' 
            ELSE 'TESTE'
        END AS ds_tipo_cartao,
        a.ds_cancel_reason AS ds_motivo_cancelamento,
        a.ds_channel_emission AS ds_canal_emissao,
        a.ds_card_version AS ds_via_cartao, 
        a.cd_card_design AS cd_tipo_cartao_origem,
        a.ds_card_design AS ds_tipo_cartao_origem,
        a.nr_card AS nr_cartao,
        a.dt_registration AS dt_cadastro,
        a.tm_registration AS hr_cadastro,
        a.dt_print AS dt_impressao,
        a.tm_print AS hr_impressao,
        a.nr_print AS nr_impressao,
        b.cd_user AS cd_usuario, ds_status_user ds_status_usuario,
        b.nm_user AS ds_nome_usuario,
        b.dt_birth AS dt_nascimento_usuario,
        b.cd_state AS cd_uf,
        b.nm_city AS nm_cidade,
        CASE
            WHEN a.nr_registered_number_cpf IS NULL THEN 'I'
            WHEN SUBSTR(LPAD(a.nr_registered_number_cpf,11), 9, 1) = '8' THEN 'S'
            ELSE 'N'
        END AS fl_emissao_sp,
        CASE
            WHEN a.cd_card_design = '7' THEN 'PURO TRANSPORTE'
            WHEN a.cd_card_design = '17' THEN 'HÍBRIDO'
            WHEN a.cd_card_design = '01' THEN 'OPERACIONAL'
            WHEN a.cd_card_design = '02' THEN 'PURO TRANSPORTE' 
            ELSE 'TESTE'
        END AS ds_tipo_cartao_simplificado,
        app.dt_create AS dt_compra,
        app.vl_recharge, fl_chip_mifare_plus ,
        CASE 
            WHEN delivery.nr_cpf IS NULL THEN 'LOJA' 
            ELSE 'DOMICÍLIO'
        END ds_tipo_entrega

    FROM 
        prd-autopass-bi-001.itg.vw_itg_mrd_top001_user b
    INNER JOIN 
        prd-autopass-bi-001.itg.vw_itg_trs_top001_card_emission a 
    ON 
        a.cd_user = b.cd_user
    LEFT JOIN 
        prd-autopass-bi-001.itg.vw_itg_trs_top001_credit_sale_app app 
    ON 
        a.nr_card = app.nr_card
    LEFT JOIN (SELECT DISTINCT nr_registered_number_emission nr_cpf
                FROM prd-autopass-bi-001.itg.vw_itg_trs_pkm001_card_delivery) delivery
    ON delivery.nr_cpf = a.nr_registered_number_cpf

    UNION ALL 

    SELECT
        'BOM' ds_origem,
        a.ts_processing,
        a.cd_system_source AS cd_origem_sistema,
        a.nr_registered_number_cpf,
        SHA256(a.nr_registered_number_cpf) AS cpf_hash,
        CONCAT(CAST(a.dt_print AS STRING), ' ', CAST(a.tm_print AS STRING)) AS dh_impressao,
        a.ds_long_remote_printer AS ds_impressora,
        a.ds_print_status AS ds_status_impressao,  
        a.cd_user_registration AS cd_usuario_impressao,
        a.ds_card_status AS ds_status_cartao,
        CASE
            WHEN a.ds_card_status = 'AGUARDANDO IMPRESSAO' AND a.ds_print_status = 'NAO IMPRESSO' THEN 'NAO IMPRESSO'
            WHEN a.ds_card_status = 'AGUARDANDO IMPRESSAO' AND a.ds_print_status = 'IMPRESSO' THEN 'NAO IMPRESSO'
            WHEN a.ds_card_status = 'ATIVO' AND a.ds_print_status = 'IMPRESSO' THEN 'IMPRESSO'
            WHEN a.ds_card_status = 'ATIVO' AND a.ds_print_status = 'ATIVO' THEN 'IMPRESSO'
            WHEN a.ds_card_status = 'ATIVO' AND a.ds_print_status = 'NAO IMPRESSO' THEN 'NAO IMPRESSO'
            WHEN a.ds_card_status = 'HOTLIST' AND a.ds_print_status = 'IMPRESSO' THEN 'IMPRESSO'
            WHEN a.ds_card_status = 'HOTLIST' AND a.ds_print_status = 'NAO IMPRESSO' THEN 'NAO IMPRESSO'
            WHEN a.ds_card_status = 'HOTLIST' AND a.ds_print_status = 'ATIVO' THEN 'IMPRESSO'
            WHEN a.ds_card_status = 'INATIVO' AND a.ds_print_status = 'IMPRESSO' THEN 'IMPRESSO'
            WHEN a.ds_card_status = 'INATIVO' AND a.ds_print_status = 'NAO IMPRESSO' THEN 'NAO IMPRESSO'
            WHEN a.ds_card_status = 'INATIVO' AND a.ds_print_status = 'ATIVO' THEN 'NAO IMPRESSO'
            WHEN a.ds_card_status = 'U' AND a.ds_print_status = 'ATIVO' THEN 'NAO IMPRESSO'
            ELSE 'NAO IMPRESSO' 
        END AS ds_status_simplificado, '' ds_status_serpro,
        CASE
            WHEN a.ds_card_design = 'TOP' THEN 'TOP' 
            WHEN a.ds_card_design = 'TOP EMV' THEN 'TOP EMV' 
            WHEN a.ds_card_design = 'OPERACIONAL' THEN 'OPERACIONAL' 
            ELSE 'TESTE'
        END AS ds_tipo_cartao,
        a.ds_cancel_reason AS ds_motivo_cancelamento,
        a.ds_channel_emission AS ds_canal_emissao,
        a.ds_card_version AS ds_via_cartao,
        a.cd_card_design AS cd_tipo_cartao_origem,
        a.ds_card_design AS ds_tipo_cartao_origem,
        a.nr_card AS nr_cartao,
        a.dt_registration AS dt_cadastro,
        a.tm_registration AS hr_cadastro,
        a.dt_print AS dt_impressao,
        a.tm_print AS hr_impressao,
        a.nr_print AS nr_impressao,
        b.cd_user AS cd_usuario, ds_status_user ds_status_usuario,
        b.nm_user AS ds_nome_usuario,
        b.dt_birth AS dt_nascimento_usuario,
        b.cd_state AS cd_uf,
        b.nm_city AS nm_cidade,
        CASE
            WHEN a.nr_registered_number_cpf IS NULL THEN 'I'
            WHEN SUBSTR(LPAD(a.nr_registered_number_cpf,11), 9, 1) = '8' THEN 'S'
            ELSE 'N'
        END AS fl_emissao_sp,
        CASE
            WHEN a.cd_card_design = '7' THEN 'PURO TRANSPORTE'
            WHEN a.cd_card_design = '17' THEN 'HÍBRIDO'
            WHEN a.cd_card_design = '01' THEN 'OPERACIONAL'
            WHEN a.cd_card_design = '02' THEN 'PURO TRANSPORTE' 
            ELSE 'TESTE'
        END AS ds_tipo_cartao_simplificado,
        app.dt_create AS dt_compra,
        app.vl_recharge, 0 fl_chip_mifare_plus,
        'N/A' ds_tipo_entrega
    FROM 
        prd-autopass-bi-001.itg.vw_itg_mrd_bom001_user b
    INNER JOIN 
        prd-autopass-bi-001.itg.vw_itg_trs_bom001_card_emission a 
    ON 
        a.cd_user = b.cd_user
    LEFT JOIN 
        prd-autopass-bi-001.itg.vw_itg_trs_bom001_credit_sale_app app 
    ON 
        a.nr_card = app.nr_card
),
remocao_card_duplicado AS (
    SELECT 
        ds_origem,
        ts_processing,
        cd_origem_sistema,
        nr_registered_number_cpf,
        cpf_hash,
        dh_impressao,
        ds_impressora,
        ds_status_impressao,  
        cd_usuario_impressao,
        ds_status_cartao,
        ds_status_simplificado, ds_status_serpro,
        ds_tipo_cartao,
        ds_motivo_cancelamento,
        ds_canal_emissao,
        ds_via_cartao,
        cd_tipo_cartao_origem,
        ds_tipo_cartao_origem,
        nr_cartao,
        dt_cadastro,
        hr_cadastro,
        dt_impressao,
        hr_impressao,
        nr_impressao,
        cd_usuario, ds_status_usuario,
        ds_nome_usuario,
        dt_nascimento_usuario,
        cd_uf,
        nm_cidade,
        fl_emissao_sp,
        ds_tipo_cartao_simplificado,
        MIN(dt_compra) AS dt_primeira_compra, -- ADICIONA A PRIMEIRA DATA DE COMPRA
        CAST(TRUNC(DATE_DIFF(current_date, dt_nascimento_usuario, DAY)/365.25) AS INTEGER) AS nr_idade,
        ROW_NUMBER() OVER (PARTITION BY nr_cartao ORDER BY dt_impressao DESC) AS linha,
        fl_chip_mifare_plus,
        ds_tipo_entrega
    FROM 
        agrupador_produto
    GROUP BY
        ds_origem, ts_processing, cd_origem_sistema, nr_registered_number_cpf, cpf_hash, dh_impressao, ds_impressora, ds_status_impressao, 
        cd_usuario_impressao, ds_status_cartao, ds_status_simplificado, ds_tipo_cartao, 
        ds_motivo_cancelamento, ds_canal_emissao, ds_via_cartao, ds_tipo_cartao_origem, 
        nr_cartao, dt_cadastro, hr_cadastro, dt_impressao, hr_impressao, nr_impressao, 
        cd_usuario, ds_nome_usuario, dt_nascimento_usuario, cd_uf, nm_cidade, fl_emissao_sp, 
        ds_tipo_cartao_simplificado, ds_status_serpro, cd_tipo_cartao_origem, ds_status_usuario, fl_chip_mifare_plus, ds_tipo_entrega
)
SELECT 
    ds_origem,
    ts_processing as dh_atualizacao,
    cd_origem_sistema,
    nr_registered_number_cpf,
    cpf_hash,
    dh_impressao,
    CASE 
        WHEN ds_tipo_cartao = 'TOP EMV' AND ds_impressora = 'IMPRESSORA NÃO IDENTIFICADA' THEN 'PEFISA'
        ELSE ds_impressora
    END AS ds_impressora,
    ds_status_impressao,  
    cd_usuario_impressao,
    ds_status_cartao,
    ds_status_simplificado, ds_status_serpro,
    ds_tipo_cartao,
    ds_motivo_cancelamento,
    ds_canal_emissao,
    ds_via_cartao,
    cd_tipo_cartao_origem,
    ds_tipo_cartao_origem,
    nr_cartao,
    dt_cadastro,
    hr_cadastro,
    dt_impressao,
    hr_impressao,
    EXTRACT(HOUR FROM hr_impressao) AS hr_impressao_curta,
    nr_impressao,
    cd_usuario, ds_status_usuario,
    ds_nome_usuario,
    dt_nascimento_usuario,
    cd_uf,
    nm_cidade,
    fl_emissao_sp,
    ds_tipo_cartao_simplificado,
    nr_idade,
    dt_primeira_compra dt_primeira_compra, --app
    CASE 
      WHEN DATE_DIFF(dt_primeira_compra, dt_impressao, DAY) <= 30 
      THEN 'Elegível' ELSE 'Não Elegível' 
    END fl_elegibilidade, -- INCLUI A PRIMEIRA DATA DE COMPRA NO RESULTADO FINAL
    fl_chip_mifare_plus,
    ds_tipo_entrega
FROM 
    remocao_card_duplicado
WHERE 
    linha = 1