config {
  type: "table",
  schema: "day",
  name: "tb_day_trs_tpd001_changedetails",
  tags: ["topdesk"],
  description: "Detalhes de changes do TOPdesk com cast de tipos"
}

SELECT
  CAST(id                 AS STRING)    AS id,
  CAST(changeNumber       AS STRING)    AS change_number,
  CAST(briefDescription   AS STRING)    AS brief_description,
  CAST(requesterName      AS STRING)    AS requester_name,
  CAST(externalNumber     AS STRING)    AS external_number,
  CAST(archivingReasonId  AS STRING)    AS archiving_reason_id,
  CAST(assetId            AS STRING)    AS asset_id,
  CAST(creationDate       AS TIMESTAMP) AS creation_date,
    -- Campos de controle
  "TPD" AS origem,
  CURRENT_TIMESTAMP() AS dt_processamento,
  SESSION_USER() AS usuario_processamento

FROM ${ref("tb_ext_trs_tpd001_changedetails")}