config {
  type: "table",
  schema: "day",
  name: "tb_day_mrd_tpd001_changeimpacts",
  tags: ["topdesk"],
  description: "Lookup de impactos de changes"
}

SELECT
  CAST(id    AS STRING) AS id,
  CAST(name  AS STRING) AS name,
  CAST('order' AS INT64)  AS order_change_impact,
    -- Campos de controle
  "TPD" AS origem,
  CURRENT_TIMESTAMP() AS dt_processamento,
  SESSION_USER() AS usuario_processamento
  
  
  FROM ${ref("tb_ext_mrd_tpd001_changeimpacts")}