config {
  type: "table",
  schema: "day",
  name: "tb_day_mrd_tpd001_subcategories",
  tags: ["topdesk"],
  description: "Lookup de subcategorias do TOPdesk"
}

SELECT
  CAST(id             AS STRING) AS id,
  CAST(name           AS STRING) AS name,
  CAST(status         AS STRING) AS status,
  CAST('order'          AS INT64)  AS order_subcategories,
  CAST(mainCategoryId AS STRING) AS main_category_id,
    -- Campos de controle
  "TPD" AS origem,
  CURRENT_TIMESTAMP() AS dt_processamento,
  SESSION_USER() AS usuario_processamento

FROM ${ref("tb_ext_mrd_tpd001_subcategories")}
