config {
  type: "table",
  schema: "day",
  name: "tb_day_mrd_tpd001_branches",
  tags: ["topdesk"],
  description: "Lookup de branches do TOPdesk"
}

SELECT
  CAST(id                      AS STRING)    AS id,
  CAST(name                    AS STRING)    AS name,
  CAST(city                    AS STRING)    AS city,
  CAST(status                  AS STRING)    AS status,
  CAST(VATnumber               AS STRING)    AS vat_number,
  CAST(customerReferenceNumber AS STRING)    AS customer_reference_number,
  CAST(countryId               AS STRING)    AS country_id,
  CAST(accountManagerId        AS STRING)    AS account_manager_id,
  CAST(headBranchId            AS STRING)    AS head_branch_id,
  CAST(mainContactId           AS STRING)    AS main_contact_id,
  CAST(serviceWindowId         AS STRING)    AS service_window_id,
  CAST(extraAId                AS STRING)    AS extra_a_id,
  CAST(extraBId                AS STRING)    AS extra_b_id,
  CAST(creationDate            AS TIMESTAMP) AS creation_date,
  CAST(modificationDate        AS TIMESTAMP) AS modification_date,
    -- Campos de controle
  "TPD" AS origem,
  CURRENT_TIMESTAMP() AS dt_processamento,
  SESSION_USER() AS usuario_processamento

FROM ${ref("tb_ext_mrd_tpd001_branches")}
