config {
  type: "table",
  schema: "day",
  name: "tb_day_mrd_tpd001_problemurgencies",
  tags: ["topdesk"],
  description: "Lista de assets ATM do TOPdesk"
}


SELECT
   
    id ,
    name ,
    `order` ,
    -- Campos de controle
  "TPD" AS origem,
  CURRENT_TIMESTAMP() AS dt_processamento,
  SESSION_USER() AS usuario_processamento

FROM ${ref("tb_ext_mrd_tpd001_problemurgencies")}
