config {
  type: "table",
  schema: "day",
  name: "tb_day_mrd_tpd001_asseteqatmdetaillist",
  tags: ["topdesk"],
  description: "Lista de assets ATM do TOPdesk"
}


SELECT
    Archived,
    ArchivedReasonId,
    CAST(CreationDate AS TIMESTAMP) AS CreationDate,
    Id,
    CAST(ModificationDate AS TIMESTAMP) AS ModificationDate,
    Name,
    Status,
    TemplateId,
    aplicacao,
    atmid,
    enderecoip1,
    fixacao,
    fornecedor,
    gateway,
    grupopdv,
    idayit,
    idbom,
    idbu,
    idqrcode,
    idtop,
    impressora,
    marcamodelo,
    observacao,
    pdv,
    produto,
    specification,
    tipoctf,
    tipodaatm,
    transacional,
    -- Campos de controle
  "TPD" AS origem,
  CURRENT_TIMESTAMP() AS dt_processamento,
  SESSION_USER() AS usuario_processamento

FROM ${ref("tb_ext_mrd_tpd001_asseteqatmdetaillist")}
