config {
  type: "table",
  schema: "day",
  name: "tb_day_mrd_tpd001_branches",
  tags: ["topdesk"],
  description: "Lookup de branches do TOPdesk"
}

SELECT
  id,                          
  name  ,                     
  city ,                      
  status   ,                   
  VATnumber ,                  
  customerReferenceNumber   ,  
  countryId    ,               
  accountManagerId  ,          
  headBranchId   ,             
  mainContactId   ,           
  serviceWindowId  ,           
  extraAId   ,                 
  extraBId ,                   
  CAST(creationDate            AS TIMESTAMP) AS creationDate,
  CAST(modificationDate        AS TIMESTAMP) AS modificationDate,
    -- Campos de controle
  "TPD" AS origem,
  CURRENT_TIMESTAMP() AS dt_processamento,
  SESSION_USER() AS usuario_processamento

FROM ${ref("tb_ext_mrd_tpd001_branches")}
