config {
  type: "table",
  schema: "day",
  name: "tb_day_mrd_tpd001_incidenturgencies",
  tags: ["topdesk"],
  description: "Lookup de subcategorias do TOPdesk"
}


SELECT
    id,
    name,
    `order` AS order_incidenturgencies,
    
  "TPD" AS origem,
  CURRENT_TIMESTAMP() AS dt_processamento,
  SESSION_USER() AS usuario_processamento

FROM ${ref("tb_ext_mrd_tpd001_incidenturgencies")}
