config {
  type: "table",
  schema: "day",
  name: "tb_day_mrd_tpd001_incidentpriorities",
  tags: ["topdesk"],
  description: "Lookup de subcategorias do TOPdesk"
}


SELECT 
    archieve,
    id,
    line1DurationId,
    line2DurationId,
    name,
    `order` as order_incidentpriorities,
    responseTimeId,
    
  "TPD" AS origem,
  CURRENT_TIMESTAMP() AS dt_processamento,
  SESSION_USER() AS usuario_processamento

FROM ${ref("tb_ext_mrd_tpd001_incidentpriorities")}



