config {
  type: "table",
  schema: "day",
  name: "tb_day_mrd_tpd001_assetroomassignments",
  tags: ["topdesk"],
  description: "Lookup de branches do TOPdesk"
}

SELECT
assetId,
    effectiveBranchId,
    id,
    inheritanceParentId,
    roomId,
    typeId,
    -- Campos de controle
  "TPD" AS origem,
  CURRENT_TIMESTAMP() AS dt_processamento,
  SESSION_USER() AS usuario_processamento

FROM ${ref("tb_ext_mrd_tpd001_assetroomassignments")}
