config {
  type: "table",
  schema: "day",
  name: "tb_day_trs_tmob001_sam_samtransactionfull",
  description: "Lista de assets ATM do TOPdesk",
  tags: ["m1"],
}



SELECT 
sstf_id,
sat_code,
stt_code,
sitfp_id,
sstf_date,
sstf_samserie,
sstf_samissuer,
sstf_samtype,
sstf_samsequence,
sstf_samcsn,
sstf_value,
sstf_balance,
sstf_transactioncounter,
sstf_rechargecounter,
sstf_token,
sstf_signature,
sstf_externalid,
sstf_mediacsn,
sstf_mediaproduct,
sstf_mediaproductversion,
sstf_mediasizeinkb,
sstf_mediacounter,
sstf_samserverid,
sstf_createdat,
sstf_updatedat,
sstf_blameuser
FROM ${ref("tb_ext_trs_tmob001_sam_samtransactionfull")}