config {
  type: "table",
  schema: "day",
  name: "tb_day_mrd_tmb001_sam_media",
  description: "Tabela dimensao",
  tags: ["commercial"],
}


SELECT 
id,
  model ,
  csn  ,
  ToIssuerId  ,
  samType ,
  samSequence ,
  version ,
  persoDate   ,
  blameUser   ,
  SAFE_CAST(createdAt AS TIMESTAMP)        AS createdAt,
  updatedAt   ,
  samParentCsn,
-- Campos de controle
  "TMB001" AS origem,
  CURRENT_TIMESTAMP() AS dt_processamento,
  SESSION_USER() AS usuario_processamento

FROM ${ref("tb_ext_mrd_tmb001_sam_media")}