-- CREATE OR REPLACE TABLE itg.tb_itg_trs_top001_redemption
-- PARTITION BY dt_process_start
-- CLUSTER BY cd_clearing, cd_issuer, ds_transport_provider, ds_consortium
-- AS
--query visão REMIÇÃO

config {
    type: "table", 
    schema: "itg",
    description: "Tabela itg de vendas por cartão ",
    tags: ["itg"],
    bigquery: {
        partitionBy: "dt_process_start",
        clusterBy: ["cd_clearing", "cd_issuer", "ds_transport_provider", "ds_consortium"]
    }
}
SELECT
  cd_clearing
, dt_process_start
, dt_card_usage
, cd_process_batch
, cd_device_log_file
, nm_device_log_file --incluido em 12/11/2025
, dt_connection
,CASE
  WHEN ds_short_application = 'QRCODE' THEN 'TRILHO'
  WHEN ds_consortium in( "CPTM", "METRO" , "BNT") THEN "TRILHO"  
  ELSE  "PNEU"
END ds_modal
, ds_consortium
,CASE
  WHEN ds_consortium = 'ABC SISTEMA DE TRANSPORTE SPE S.A.' THEN 'INTERMUNICIPAL'
  WHEN ds_consortium = 'AREA 5' THEN 'INTERMUNICIPAL'
  WHEN ds_consortium = 'BNT' THEN 'BNT'
  WHEN ds_consortium IN ('METRO','CPTM','VIAQUATRO','VIAMOBILIDADE') THEN 'BNT'
  WHEN ds_consortium = 'CONSORCIO ANHANGUERA' THEN 'INTERMUNICIPAL'
  WHEN ds_consortium = 'CONSORCIO INTERNORTE' THEN 'INTERMUNICIPAL'
  WHEN ds_consortium = 'CONSORCIO INTERVIAS' THEN 'INTERMUNICIPAL'
  WHEN ds_consortium = 'CONSORCIO UNILESTE' THEN 'INTERMUNICIPAL'
  WHEN ds_consortium = 'OUTROS' THEN 'MUNICIPAL'
  WHEN ds_consortium = 'RTO EMTU' THEN 'RTO'
  WHEN ds_consortium = 'PERMISSIONARIAS' THEN 'OUTROS'
  WHEN ds_consortium IS NULL THEN 'CONSÓRCIO NÃO ESPECIFICADO'
ELSE 'VERIFICAR' END ds_consortium_group --incluido em 03/06/2024
, ds_transport_provider
, cd_issuer
, cd_application
, ds_short_application
    produto_agrupado,
    valorado,
    repasse_clearing,
    comissionamento
--, core.fn_aut001_application_format(ds_short_application) ds_short_application_agg --ADICIONADO 10/12/2025
, cd_transport_provider
, cd_status
, case
  when ds_short_application = 'QRCODE' then  'QRCODE'
  -- when ds_short_application = 'EMV' then  'EMV' alterado por Patucci dia 02/03/2026 devido a inclusão das aplicações 180 e 181 -- EMV CRÉDITO E EMV DÉBITO
  when ds_short_application like '%EMV%' then  'EMV'
  else 'TOP'
  end ds_product_group
, cd_vehicle --incluido em 12/11/2025
, nm_station --ADICIONADO 12/12/2024
, core.fn_aut001_nm_station_format(nm_station) nm_station_agg --ADICIONADO 10/12/2025
, nm_line --ADICIONADO 12/12/2024
--, core.fn_aut001_nm_line_format(nm_line) nm_line_agg --ADICIONADO 10/12/2025
, qt_redemption
, vl_fare
, vl_clearing_payment
, ts_processing
, cd_company
, nr_load_control
, cd_created_by
, cd_system_source
FROM (
      SELECT
        cp.cd_clearing cd_clearing
      , cl.dt_process_start dt_process_start
      , cp.dt_card_usage
      , dlf.cd_process_batch
      , dlf.cd_device_log_file
      , dlf.nm_device_log_file
      , dlf.dt_connection
      , tp.ds_transport_provider ds_transport_provider
      , tp.cd_status
      , udf.cd_vehicle
      , CASE
          WHEN c.ds_consortium IS NULL OR c.ds_consortium = 'ARQUIVOS INCONSISTENTES' OR c.ds_consortium = 'AUTOPASS' THEN 'MUNICIPAL'
          ELSE c.ds_consortium  --regra alterada em 28/08
        END AS ds_consortium
      , cp.cd_issuer cd_issuer

      , cp.cd_application --incluido em 22/10
      , B.displayName ds_short_application,
      B.produto_agrupado,
      B.valorado,
      B.repasse_clearing,
      B.comissionamento
      , cp.cd_transport_provider
      , COUNT(*) qt_redemption
      , SUM(cp.vl_fare) vl_fare
      , SUM(cp.vl_clearing_payment) vl_clearing_payment
      , CURRENT_TIMESTAMP() ts_processing
      , cp.cd_company cd_company
      , CAST(FORMAT_TIMESTAMP("%Y%m%d%H%M%S", CURRENT_TIMESTAMP()) AS INT64) nr_load_control
      , SESSION_USER() cd_created_by
      , cp.cd_system_source cd_system_source
      , ld.ds_long nm_station --ESTACAO ADICIONADO 12/12/2024
      , lm.ds_long nm_line --LINHA ADICIONADO 12/12/2024
      FROM his.tb_his_trs_top001_clearing_payment cp

      -- INNER JOIN his.tb_his_mrd_top001_application app
      -- ON app.cd_application = cp.cd_application
      -- AND app.cd_issuer = '14'
      -- AND app.cd_status = 'A'

     LEFT JOIN  `prd-autopass-ed-001.ext.tb_ext_mrd_tmb001_dim_produto`  B
      ON cp.cd_application = B.code
      AND cp.cd_issuer = B.toIssuerCode


      LEFT OUTER JOIN his.tb_his_mrd_top001_line_detail ld
      ON cp.cd_line_detail = ld.cd_line_detail
      LEFT OUTER JOIN his.tb_his_mrd_top001_line lm
      ON ld.cd_line = lm.cd_line
      LEFT OUTER JOIN his.tb_his_trs_top001_device_log dl  --regra acertada em 20/09
      ON dl.cd_device_log_file = cp.cd_device_log_file
      AND dl.cd_process_batch = cp.cd_process_batch
      AND dl.cd_device_log = cp.cd_device_log
      AND dl.cd_device_log_detail = cp.cd_device_log_detail
      LEFT OUTER JOIN his.tb_his_mrd_top001_transport_provider tp
      ON tp.cd_transport_provider = cp.cd_transport_provider
 
      LEFT OUTER JOIN his.tb_his_mrd_top001_transport_provider_consortium tpc
      --(SELECT * FROM his.tb_his_mrd_top001_transport_provider_consortium WHERE (cd_transport_provider NOT IN ('2') AND cd_consortium NOT IN ('9'))) tpc
      ON tpc.cd_transport_provider = cp.cd_transport_provider
 
      LEFT OUTER JOIN his.tb_his_mrd_top001_consortium c
      ON c.cd_consortium = tpc.cd_consortium
      LEFT JOIN his.tb_his_trs_top001_clearing cl
      ON cp.cd_clearing = cl.cd_clearing
      LEFT JOIN his.tb_his_trs_top001_device_log_file dlf
      ON dlf.cd_process_batch = cp.cd_process_batch
      AND dlf.cd_device_log_file = cp.cd_device_log_file
      LEFT JOIN his.tb_his_trs_top001_usage_data_file udf
      ON  cp.cd_process_batch = udf.cd_process_batch
      and cp.cd_usage_data_file = udf.cd_usage_data_file
      WHERE 1 = 1
      AND (cp.nr_part_fare = '1' OR cp.nr_part_fare IS NULL)
      GROUP BY all
)