config {
    type: "table",
    schema: "dfl",
    description: "Tabela master do clearing com diversas origens ",
    tags: ["commercial"],
    bigquery: {
        partitionBy: "DATE(ts_transacao_tz)",
    }
}


SELECT

    FORMAT_DATETIME('%d/%m/%Y %H:%M:%S', ct.ctm_datetime_tz) AS ts_transacao,--data_hora_trans,
    ct.ctm_datetime_tz               AS ts_transacao_tz,  
    ct.ctm_id                        AS cd_transacao,--idtrn,
    dd.tu_code                       AS cd_atm, --cod_atm,
    tl.description                   AS ds_estacao_origem,--Estacao,
    coalesce(dp.ds_estacao,tl.description )        AS ds_estacao,--Estacao,
    filg.description                 AS ds_linha_origem, --Linha,
    coalesce(dp.ds_linha_completa,filg.description )        AS ds_linha_completa,--Linha,
    coalesce(dp.ds_linha,filg.description )        AS ds_linha,--Linha,
    op.op_desc                       AS ds_empresa_origem, --Empresa,  
    coalesce(dp.ds_empresa, op.op_desc,ds_empresa )                        AS ds_empresa, --Empresa, 
    ct.ctm_value                     AS vl_transacao,--valor,
    ct.ctm_receivedvalue             AS vl_recebido, --valor_recebido,
    ctxpm.ctmxcpm_pix_txid           AS cd_pix_tx, --pix_txid,
    ctxpm.ctmxcpm_pix_endtoendid     AS cd_pix_endtoend,--pix_endtoendid,
    mtp.code                         AS cd_med_aplicacao,--aplicacao,
    cp.cpt_id                        AS cd_aplicacao, -- usado só pra filtrar o relatorio
    cp.cp_desc                       AS ds_aplicacao,--produto,  
    'tbd'                            AS ds_pdv, --pdv,  
    CURRENT_TIMESTAMP() ts_processamento,
    SESSION_USER() ds_usuario_processamento,
    'TMB001' ds_origem_extracao
-- FROM `prd-autopass-ed-001.his.tb_his_trs_tmb001_com_tranmt` ct
FROM ${ref("tb_his_trs_tmb001_com_tranmt")} ct

-- INNER JOIN `prd-autopass-ed-001.his.tb_his_trs_tmb001_com_trandt` ctd
INNER JOIN ${ref("tb_his_trs_tmb001_com_trandt")} ctd
    ON ctd.ctm_id = ct.ctm_id

-- INNER JOIN `prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_product` cp
INNER JOIN ${ref("tb_his_mrd_tmb001_com_product")} cp
    ON cp.cp_id = ctd.cp_id

-- LEFT JOIN `prd-autopass-ed-001.his.tb_his_mrd_tmb001_medtransitproduct` mtp
LEFT JOIN ${ref("tb_his_mrd_tmb001_medtransitproduct")} mtp
    ON mtp.description = cp.cp_desc

-- INNER JOIN `prd-autopass-ed-001.his.tb_his_trs_tmb001_com_tranmt_x_payment_mode` ctxpm
INNER JOIN ${ref("tb_his_trs_tmb001_com_tranmt_x_payment_mode")} ctxpm
    ON ctxpm.ctm_id = ct.ctm_id

-- INNER JOIN `prd-autopass-ed-001.his.tb_his_mrd_tmb001_dvc_device` dd
INNER JOIN ${ref("tb_his_mrd_tmb001_dvc_device")} dd
    ON dd.dv_id = ct.dv_id

-- INNER JOIN `prd-autopass-ed-001.his.tb_his_mrd_tmb001_dvc_operator` op
INNER JOIN ${ref("tb_his_mrd_tmb001_dvc_operator")} op
    ON op.op_id = dd.op_id

-- LEFT JOIN `prd-autopass-ed-001.his.tb_his_mrd_tmb001_toline` tl
LEFT JOIN ${ref("tb_his_mrd_tmb001_toline")} tl
    ON tl.id = dd.dv_line_id

-- LEFT JOIN `prd-autopass-ed-001.his.tb_his_mrd_tmb001_farintegrationlinegroup` filg
LEFT JOIN ${ref("tb_his_mrd_tmb001_farintegrationlinegroup")} filg
    ON filg.id = tl.farIntegrationLineGroupId

-- LEFT JOIN `dev-autopass-bi-001.his.tb_his_mrd_shp001_depara_localidade_venda_atm` dp
LEFT JOIN ${ref("tb_his_mrd_shp001_depara_localidade_venda_atm")} dp
    ON dp.cd_localidade_venda = dd.dv_line_id
    AND dp.cd_origem = dd.origem

WHERE ct.ctm_status IN ('A', 'P')
  AND dd.dt_id = '7'
  AND ctxpm.cpm_id = '5'
  -- AND cp.cpt_id <> '5' -- CONDIÇÃO PARA EXPURGO DE BU
  AND ct.ctm_datetime_tz >= DATETIME('2026-05-20 00:00:00.000')


--   AND dd.dt_id = '7'
--   AND ctxpm.cpm_id = '5'
--   AND ct.ctm_datetime_tz BETWEEN DATETIME('2026-01-01 00:00:00')
--                               AND DATETIME('2026-05-31 23:59:59.999')
--  -- AND ct.ctm_id = '169445043'


