config {
    type: "table",
    schema: "dfl",
    description: "Tabela master do clearing com diversas origens ",
    tags: ["commercial"],
    bigquery: {
        partitionBy: "DATE(ctm_datetime_tz)",
    }
}


SELECT

    dd.tu_code                       AS cod_atm,
    tl.description                   AS Estacao,
    filg.description                 AS Linha,
    op.op_desc                       AS Empresa,
    FORMAT_DATETIME('%d/%m/%Y %H:%M:%S', ct.ctm_datetime_tz) AS data_hora_trans,
    ct.ctm_value                     AS valor,
    ct.ctm_receivedvalue             AS valor_recebido,
    ctxpm.ctmxcpm_pix_txid           AS pix_txid,
    ctxpm.ctmxcpm_pix_endtoendid     AS pix_endtoendid,
    cp.cp_desc                       AS produto,
    mtp.code                         AS aplicacao,
    ct.ctm_id                        AS idtrn,
    'tbd'                            AS pdv,
    ct.ctm_datetime_tz,
    cp.cpt_id -- usado só pra filtrar o relatorio

-- FROM `prd-autopass-ed-001.his.tb_his_trs_tmb001_com_tranmt` ct
FROM ${ref("tb_his_trs_tmb001_com_tranmt")} ct

-- INNER JOIN `prd-autopass-ed-001.his.tb_his_trs_tmb001_com_trandt` ctd
INNER JOIN ${ref("tb_his_trs_tmb001_com_trandt")} ctd
    ON ctd.ctm_id = ct.ctm_id

-- INNER JOIN `prd-autopass-ed-001.his.tb_his_mrd_tmb001_com_product` cp
INNER JOIN ${ref("tb_his_mrd_tmb001_com_product")} cp
    ON cp.cp_id = ctd.cp_id

-- LEFT JOIN `prd-autopass-ed-001.his.tb_his_mrd_tmb001_medtransitproduct` mtp
LEFT JOIN ${ref("tb_his_mrd_tmb001_medtransitproduct")} mtp
    ON mtp.description = cp.cp_desc

-- INNER JOIN `prd-autopass-ed-001.his.tb_his_trs_tmb001_com_tranmt_x_payment_mode` ctxpm
INNER JOIN ${ref("tb_his_trs_tmb001_com_tranmt_x_payment_mode")} ctxpm
    ON ctxpm.ctm_id = ct.ctm_id

-- INNER JOIN `prd-autopass-ed-001.his.tb_his_mrd_tmb001_dvc_device` dd
INNER JOIN ${ref("tb_his_mrd_tmb001_dvc_device")} dd
    ON dd.dv_id = ct.dv_id

-- INNER JOIN `prd-autopass-ed-001.his.tb_his_mrd_tmb001_dvc_operator` op
INNER JOIN ${ref("tb_his_mrd_tmb001_dvc_operator")} op
    ON op.op_id = dd.op_id

-- LEFT JOIN `prd-autopass-ed-001.his.tb_his_mrd_tmb001_toline` tl
LEFT JOIN ${ref("tb_his_mrd_tmb001_toline")} tl
    ON tl.id = dd.dv_line_id

-- LEFT JOIN `prd-autopass-ed-001.his.tb_his_mrd_tmb001_farintegrationlinegroup` filg
LEFT JOIN ${ref("tb_his_mrd_tmb001_farintegrationlinegroup")} filg
    ON filg.id = tl.farIntegrationLineGroupId

WHERE ct.ctm_status IN ('A', 'P')
  AND dd.dt_id = '7'
  AND ctxpm.cpm_id = '5'
  -- AND cp.cpt_id <> '5' -- CONDIÇÃO PARA EXPURGO DE BU
  AND ct.ctm_datetime_tz >= DATETIME('2026-05-20 00:00:00.000')


--   AND dd.dt_id = '7'
--   AND ctxpm.cpm_id = '5'
--   AND ct.ctm_datetime_tz BETWEEN DATETIME('2026-01-01 00:00:00')
--                               AND DATETIME('2026-05-31 23:59:59.999')
--  -- AND ct.ctm_id = '169445043'


